# site settings
title: Rajnil Mukherjee
subtitle: The Aaevelion Project
email_1: rajnilmukherjee.rm@gmail.com
email_2: ms21213@iisermohali.ac.in
description: Welcome to my website!
baseurl: #the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Rajnil Mukherjee
street_address: F6/2 Indraloke Housing Estate 3, Paikpara
city: Kolkata
state: West Bengal
zip_code: 700002
country: India
phone: +91 8017965462

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/Aaevelion
  GitLab:
  Google-Plus: 
  Instagram: https://www.instagram.com/rajnil_mukherjee/
  LinkedIn: https://www.linkedin.com/in/rajnil-mukherjee-503a5a1ba/
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
